
F ∏};æËZÊmlõÉ^¬]Nºd&J.‚ÚzÈªhﬁ¸ EÁ7	Œ>¥¢c'äÜdó‰Bã¨ˇ´^›»•`›mÓÿ
Íÿ
ûÿ
§
…ÂÈ™"autochannelà
Î
reg-comﬂ-----BEGIN CERTIFICATE-----
MIICTzCCAfWgAwIBAgIUNXhaqNOPX4wAArW755tr158h/SAwCgYIKoZIzj0EAwIw
XzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29t
MB4XDTIzMTExODIxMjM0OVoXDTMzMDgxNzIxMjM0OVowZTELMAkGA1UEBhMCVVMx
FzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYD
VQQLDAdvcmRlcmVyMRkwFwYDVQQDDBBvcmRlcmVyMS5yZWcuY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEdQ+3qBKer6B87l8jPmXQCDltDyJulPs5IxnQg9zc
Zw1lV1gUGrLUXctJp2cmahz8+kyqxTIKaRYt04bnU9we/KOBiDCBhTAOBgNVHQ8B
Af8EBAMCB4AwDAYDVR0TAQH/BAIwADBEBgNVHREEPTA7hwSsH1k0ghBvcmRlcmVy
MS5yZWcuY29tghBvcmRlcmVyMS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwHwYD
VR0jBBgwFoAUzLxUOpx043wCMmfBKKHPYftF2UowCgYIKoZIzj0EAwIDSAAwRQIh
AN+W5rWPVbubloS0ioo8HAp+4e/eVUCYINmSiNZHRW9lAiB8MSyXtDrWLHfjE6Y3
fOtxtxqxgVhvvYjbXSiibUKJgA==
-----END CERTIFICATE-----
Aœ'¨ñUIt∆)à!ºé–†…O1ÒÚøuÛ–
ìæçæ”v
Application√v¡:
example2-reg-com¨:,
AnchorPeers

172.31.89.52€6Admins¶7
MSPû7ì7ê7
example2-reg-comÌ-----BEGIN CERTIFICATE-----
MIICuDCCAl6gAwIBAgIUVSIdoSOQr+WTfOI/5xfpixs9EcUwCgYIKoZIzj0EAwIw
cjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBleGFtcGxlMi5yZWcuY29tMR0wGwYDVQQDDBRj
YTEuZXhhbXBsZTIucmVnLmNvbTAeFw0yMzExMTgyMTIzMThaFw0zMzExMTUyMTIz
MThaMHIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
A1UEBwwHUmFsZWlnaDEZMBcGA1UECgwQZXhhbXBsZTIucmVnLmNvbTEdMBsGA1UE
AwwUY2ExLmV4YW1wbGUyLnJlZy5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AAQ9cJytEzb8dwSh7vyluEqf0E728++CTm+dFDAWcNqrLgTP1NpFkXc9OWU0uj+g
RAWGTR0TN8r9QYptcvqP/ZMXo4HRMIHOMB0GA1UdDgQWBBRyBsqudtPVsvUfOsd/
Cky9pKGPgzAfBgNVHSMEGDAWgBRyBsqudtPVsvUfOsd/Cky9pKGPgzAPBgNVHRMB
Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
KwYBBQUHAwIwTAYDVR0RBEUwQ4cErB9ZNIIUY2ExLmV4YW1wbGUyLnJlZy5jb22C
FGNhMS1leGFtcGxlMi1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDSAAwRQIhAL7XOd3wn7uZgoXDCfjPaizw1GefEynN6shUJXnMX5t4AiBePLYV
qp6l8R+zPmpe3hG1snQxjEQuRwRdDB1pvX714w==
-----END CERTIFICATE-----
"å-----BEGIN CERTIFICATE-----
MIICcjCCAhigAwIBAgIUEGpa4dBx+/sQy23HQBlksYSm+eIwCgYIKoZIzj0EAwIw
cjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBleGFtcGxlMi5yZWcuY29tMR0wGwYDVQQDDBRj
YTEuZXhhbXBsZTIucmVnLmNvbTAeFw0yMzExMTgyMTIzMjNaFw0zMzA4MTcyMTIz
MjNaMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
A1UEBwwHUmFsZWlnaDEOMAwGA1UECwwFYWRtaW4xHzAdBgNVBAMMFkFkbWluQGV4
YW1wbGUyLnJlZy5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATFlZP3+uBJ
VhC4wt28hLVT4G+2HC8yHUEKkgSK+uWwQ8noGD1ur1S/l25CWqyRd0Ha8dqHk4QP
ZAacCx+8wuC8o4GUMIGRMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMFAG
A1UdEQRJMEeHBKwfWTSCFkFkbWluQGV4YW1wbGUyLnJlZy5jb22CFkFkbWluQGV4
YW1wbGUyLXJlZy1jb22CCWxvY2FsaG9zdIcEfwAAATAfBgNVHSMEGDAWgBRyBsqu
dtPVsvUfOsd/Cky9pKGPgzAKBggqhkjOPQQDAgNIADBFAiAXcQ97B+ntC1ZQHYzT
jQ/CiHf+yWk3/0Uo7d//2dhpEwIhAN9OlO4VVnXQkhQcYazHURFfHhmSPaMNrE4P
kpkFGcjY
-----END CERTIFICATE-----
B
SHA2SHA256J˝-----BEGIN CERTIFICATE-----
MIICxDCCAmqgAwIBAgIUeqm7YB/LSiCq8JhZRrd29S3yoHowCgYIKoZIzj0EAwIw
dTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBleGFtcGxlMi5yZWcuY29tMSAwHgYDVQQDDBd0
bHNjYTEuZXhhbXBsZTIucmVnLmNvbTAeFw0yMzExMTgyMTIzMThaFw0zMzExMTUy
MTIzMThaMHUxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQ
MA4GA1UEBwwHUmFsZWlnaDEZMBcGA1UECgwQZXhhbXBsZTIucmVnLmNvbTEgMB4G
A1UEAwwXdGxzY2ExLmV4YW1wbGUyLnJlZy5jb20wWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAATLey9qLGLj32EDL9HTfdZMn3LZQzEIb6oSG3qeCmAkCuR1pNLBW6WF
BREebhJCevpKHuqAD7GWeT1phj4YlLsWo4HXMIHUMB0GA1UdDgQWBBRT7EF/xXt2
6rihKe8sdCLSRcZpiDAfBgNVHSMEGDAWgBRT7EF/xXt26rihKe8sdCLSRcZpiDAP
BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEF
BQcDAQYIKwYBBQUHAwIwUgYDVR0RBEswSYcErB9ZNIIXdGxzY2ExLmV4YW1wbGUy
LnJlZy5jb22CF3Rsc2NhMS1leGFtcGxlMi1yZWctY29tgglsb2NhbGhvc3SHBH8A
AAEwCgYIKoZIzj0EAwIDSAAwRQIgW2kFpdAW2pRT9N370plO6itxiLXSmx5VbiRy
v7nNni4CIQDbkctQHxc1TXEZKzescIhrj4oKAqHSJpWNffdIsHi+yg==
-----END CERTIFICATE-----
ZÏ¯
Ì-----BEGIN CERTIFICATE-----
MIICuDCCAl6gAwIBAgIUVSIdoSOQr+WTfOI/5xfpixs9EcUwCgYIKoZIzj0EAwIw
cjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBleGFtcGxlMi5yZWcuY29tMR0wGwYDVQQDDBRj
YTEuZXhhbXBsZTIucmVnLmNvbTAeFw0yMzExMTgyMTIzMThaFw0zMzExMTUyMTIz
MThaMHIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
A1UEBwwHUmFsZWlnaDEZMBcGA1UECgwQZXhhbXBsZTIucmVnLmNvbTEdMBsGA1UE
AwwUY2ExLmV4YW1wbGUyLnJlZy5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AAQ9cJytEzb8dwSh7vyluEqf0E728++CTm+dFDAWcNqrLgTP1NpFkXc9OWU0uj+g
RAWGTR0TN8r9QYptcvqP/ZMXo4HRMIHOMB0GA1UdDgQWBBRyBsqudtPVsvUfOsd/
Cky9pKGPgzAfBgNVHSMEGDAWgBRyBsqudtPVsvUfOsd/Cky9pKGPgzAPBgNVHRMB
Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
KwYBBQUHAwIwTAYDVR0RBEUwQ4cErB9ZNIIUY2ExLmV4YW1wbGUyLnJlZy5jb22C
FGNhMS1leGFtcGxlMi1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDSAAwRQIhAL7XOd3wn7uZgoXDCfjPaizw1GefEynN6shUJXnMX5t4AiBePLYV
qp6l8R+zPmpe3hG1snQxjEQuRwRdDB1pvX714w==
-----END CERTIFICATE-----
clientˆ
Ì-----BEGIN CERTIFICATE-----
MIICuDCCAl6gAwIBAgIUVSIdoSOQr+WTfOI/5xfpixs9EcUwCgYIKoZIzj0EAwIw
cjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBleGFtcGxlMi5yZWcuY29tMR0wGwYDVQQDDBRj
YTEuZXhhbXBsZTIucmVnLmNvbTAeFw0yMzExMTgyMTIzMThaFw0zMzExMTUyMTIz
MThaMHIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
A1UEBwwHUmFsZWlnaDEZMBcGA1UECgwQZXhhbXBsZTIucmVnLmNvbTEdMBsGA1UE
AwwUY2ExLmV4YW1wbGUyLnJlZy5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AAQ9cJytEzb8dwSh7vyluEqf0E728++CTm+dFDAWcNqrLgTP1NpFkXc9OWU0uj+g
RAWGTR0TN8r9QYptcvqP/ZMXo4HRMIHOMB0GA1UdDgQWBBRyBsqudtPVsvUfOsd/
Cky9pKGPgzAfBgNVHSMEGDAWgBRyBsqudtPVsvUfOsd/Cky9pKGPgzAPBgNVHRMB
Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
KwYBBQUHAwIwTAYDVR0RBEUwQ4cErB9ZNIIUY2ExLmV4YW1wbGUyLnJlZy5jb22C
FGNhMS1leGFtcGxlMi1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDSAAwRQIhAL7XOd3wn7uZgoXDCfjPaizw1GefEynN6shUJXnMX5t4AiBePLYV
qp6l8R+zPmpe3hG1snQxjEQuRwRdDB1pvX714w==
-----END CERTIFICATE-----
peer"˜
Ì-----BEGIN CERTIFICATE-----
MIICuDCCAl6gAwIBAgIUVSIdoSOQr+WTfOI/5xfpixs9EcUwCgYIKoZIzj0EAwIw
cjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBleGFtcGxlMi5yZWcuY29tMR0wGwYDVQQDDBRj
YTEuZXhhbXBsZTIucmVnLmNvbTAeFw0yMzExMTgyMTIzMThaFw0zMzExMTUyMTIz
MThaMHIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
A1UEBwwHUmFsZWlnaDEZMBcGA1UECgwQZXhhbXBsZTIucmVnLmNvbTEdMBsGA1UE
AwwUY2ExLmV4YW1wbGUyLnJlZy5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AAQ9cJytEzb8dwSh7vyluEqf0E728++CTm+dFDAWcNqrLgTP1NpFkXc9OWU0uj+g
RAWGTR0TN8r9QYptcvqP/ZMXo4HRMIHOMB0GA1UdDgQWBBRyBsqudtPVsvUfOsd/
Cky9pKGPgzAfBgNVHSMEGDAWgBRyBsqudtPVsvUfOsd/Cky9pKGPgzAPBgNVHRMB
Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
KwYBBQUHAwIwTAYDVR0RBEUwQ4cErB9ZNIIUY2ExLmV4YW1wbGUyLnJlZy5jb22C
FGNhMS1leGFtcGxlMi1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDSAAwRQIhAL7XOd3wn7uZgoXDCfjPaizw1GefEynN6shUJXnMX5t4AiBePLYV
qp6l8R+zPmpe3hG1snQxjEQuRwRdDB1pvX714w==
-----END CERTIFICATE-----
admin*˘
Ì-----BEGIN CERTIFICATE-----
MIICuDCCAl6gAwIBAgIUVSIdoSOQr+WTfOI/5xfpixs9EcUwCgYIKoZIzj0EAwIw
cjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBleGFtcGxlMi5yZWcuY29tMR0wGwYDVQQDDBRj
YTEuZXhhbXBsZTIucmVnLmNvbTAeFw0yMzExMTgyMTIzMThaFw0zMzExMTUyMTIz
MThaMHIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
A1UEBwwHUmFsZWlnaDEZMBcGA1UECgwQZXhhbXBsZTIucmVnLmNvbTEdMBsGA1UE
AwwUY2ExLmV4YW1wbGUyLnJlZy5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AAQ9cJytEzb8dwSh7vyluEqf0E728++CTm+dFDAWcNqrLgTP1NpFkXc9OWU0uj+g
RAWGTR0TN8r9QYptcvqP/ZMXo4HRMIHOMB0GA1UdDgQWBBRyBsqudtPVsvUfOsd/
Cky9pKGPgzAfBgNVHSMEGDAWgBRyBsqudtPVsvUfOsd/Cky9pKGPgzAPBgNVHRMB
Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
KwYBBQUHAwIwTAYDVR0RBEUwQ4cErB9ZNIIUY2ExLmV4YW1wbGUyLnJlZy5jb22C
FGNhMS1leGFtcGxlMi1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
AwIDSAAwRQIhAL7XOd3wn7uZgoXDCfjPaizw1GefEynN6shUJXnMX5t4AiBePLYV
qp6l8R+zPmpe3hG1snQxjEQuRwRdDB1pvX714w==
-----END CERTIFICATE-----
ordererAdmins"W
WritersLB>
 
example2-reg-com
example2-reg-comAdmins":
Admins0&" 
example2-reg-comAdmins"?
Endorsement0&" 
example2-reg-comAdmins"s
Readersh^Z 
example2-reg-com
example2-reg-com
example2-reg-comAdmins*Admins˚9
example-reg-comÁ9,
AnchorPeers

172.31.89.52⁄6AdminsË6
MSP‡6’6“6
example-reg-comÂ-----BEGIN CERTIFICATE-----
MIICsjCCAligAwIBAgIUNYpxL3n+Z6YXTBf/9gtk9QREBgYwCgYIKoZIzj0EAwIw
cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRgwFgYDVQQKDA9leGFtcGxlLnJlZy5jb20xHDAaBgNVBAMME2Nh
MS5leGFtcGxlLnJlZy5jb20wHhcNMjMxMTE4MjEyMjU4WhcNMzMxMTE1MjEyMjU4
WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNV
BAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2V4YW1wbGUucmVnLmNvbTEcMBoGA1UEAwwT
Y2ExLmV4YW1wbGUucmVnLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDvM
1ZgErFVgMy8gd8ChGvax9HzHHGfykPBRgxR/7DCFaKjsSqX3sO7RHU4iXaKdXTLN
WwZ5YREFyQs82vwBB2ujgc8wgcwwHQYDVR0OBBYEFJ5TxF1Te/jx0i5iCvURURRC
87gNMB8GA1UdIwQYMBaAFJ5TxF1Te/jx0i5iCvURURRC87gNMA8GA1UdEwEB/wQF
MAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF
BQcDAjBKBgNVHREEQzBBhwSsH1k0ghNjYTEuZXhhbXBsZS5yZWcuY29tghNjYTEt
ZXhhbXBsZS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAw
RQIgYcG1pQrPfndHWJAj4QFEqFgvaAx/7oE15zmm9/XiQHoCIQCcjWPaGMT5u33c
ucZHCHqAmfw0SXJSgjcQSV954KDXsQ==
-----END CERTIFICATE-----
"É-----BEGIN CERTIFICATE-----
MIICbDCCAhOgAwIBAgIUPVi9lgejQQCWGxJQkkgF1iPG4wEwCgYIKoZIzj0EAwIw
cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRgwFgYDVQQKDA9leGFtcGxlLnJlZy5jb20xHDAaBgNVBAMME2Nh
MS5leGFtcGxlLnJlZy5jb20wHhcNMjMxMTE4MjEyMzA0WhcNMzMwODE3MjEyMzA0
WjBoMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNV
BAcMB1JhbGVpZ2gxDjAMBgNVBAsMBWFkbWluMR4wHAYDVQQDDBVBZG1pbkBleGFt
cGxlLnJlZy5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASkk0jiwVc5SUKu
MzuLDQyYiK8btACijyOdyFJ0ZeifELEnK1qf8+Ih8kgzhemvZWOAiVTZg2MtlVSE
iOl1s1poo4GSMIGPMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAME4GA1Ud
EQRHMEWHBKwfWTSCFUFkbWluQGV4YW1wbGUucmVnLmNvbYIVQWRtaW5AZXhhbXBs
ZS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwHwYDVR0jBBgwFoAUnlPEXVN7+PHS
LmIK9RFRFELzuA0wCgYIKoZIzj0EAwIDRwAwRAIgIDWa/yHincoUKgkcLaZa5Tjp
ixg/uCb4zTBr8O8fuXgCIGBQE+9cA3Mi/0Li5kPIof17pFs9Hf2BqkUXCFdPoM2H
-----END CERTIFICATE-----
B
SHA2SHA256JÒ-----BEGIN CERTIFICATE-----
MIICvTCCAmSgAwIBAgIUcAtfKsJOFMIIdiJHJP4OIYBIhUMwCgYIKoZIzj0EAwIw
czELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRgwFgYDVQQKDA9leGFtcGxlLnJlZy5jb20xHzAdBgNVBAMMFnRs
c2NhMS5leGFtcGxlLnJlZy5jb20wHhcNMjMxMTE4MjEyMjU5WhcNMzMxMTE1MjEy
MjU5WjBzMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAO
BgNVBAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2V4YW1wbGUucmVnLmNvbTEfMB0GA1UE
AwwWdGxzY2ExLmV4YW1wbGUucmVnLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEH
A0IABKLm8Xi6KHm91fB6Dw0mtDbLeD+/j5VPwv9Q6yHgiBYH07vMA4fGTey+w9il
hpC0KV2fNxZQwEjY7M5E8I+L7wCjgdUwgdIwHQYDVR0OBBYEFLM7goTl/KLp5B+d
GXlO1CjSKXhuMB8GA1UdIwQYMBaAFLM7goTl/KLp5B+dGXlO1CjSKXhuMA8GA1Ud
EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMB
BggrBgEFBQcDAjBQBgNVHREESTBHhwSsH1k0ghZ0bHNjYTEuZXhhbXBsZS5yZWcu
Y29tghZ0bHNjYTEtZXhhbXBsZS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYI
KoZIzj0EAwIDRwAwRAIgNRmBvEMfyo7RSe0MVlTVC7m+zaOAXn76uIpRTA70xkMC
IDAF69gdeINmpSMOd7GnHiOpRacexXS3k0oNlMB4IfMS
-----END CERTIFICATE-----
ZÃ
Â-----BEGIN CERTIFICATE-----
MIICsjCCAligAwIBAgIUNYpxL3n+Z6YXTBf/9gtk9QREBgYwCgYIKoZIzj0EAwIw
cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRgwFgYDVQQKDA9leGFtcGxlLnJlZy5jb20xHDAaBgNVBAMME2Nh
MS5leGFtcGxlLnJlZy5jb20wHhcNMjMxMTE4MjEyMjU4WhcNMzMxMTE1MjEyMjU4
WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNV
BAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2V4YW1wbGUucmVnLmNvbTEcMBoGA1UEAwwT
Y2ExLmV4YW1wbGUucmVnLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDvM
1ZgErFVgMy8gd8ChGvax9HzHHGfykPBRgxR/7DCFaKjsSqX3sO7RHU4iXaKdXTLN
WwZ5YREFyQs82vwBB2ujgc8wgcwwHQYDVR0OBBYEFJ5TxF1Te/jx0i5iCvURURRC
87gNMB8GA1UdIwQYMBaAFJ5TxF1Te/jx0i5iCvURURRC87gNMA8GA1UdEwEB/wQF
MAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF
BQcDAjBKBgNVHREEQzBBhwSsH1k0ghNjYTEuZXhhbXBsZS5yZWcuY29tghNjYTEt
ZXhhbXBsZS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAw
RQIgYcG1pQrPfndHWJAj4QFEqFgvaAx/7oE15zmm9/XiQHoCIQCcjWPaGMT5u33c
ucZHCHqAmfw0SXJSgjcQSV954KDXsQ==
-----END CERTIFICATE-----
clientÓ
Â-----BEGIN CERTIFICATE-----
MIICsjCCAligAwIBAgIUNYpxL3n+Z6YXTBf/9gtk9QREBgYwCgYIKoZIzj0EAwIw
cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRgwFgYDVQQKDA9leGFtcGxlLnJlZy5jb20xHDAaBgNVBAMME2Nh
MS5leGFtcGxlLnJlZy5jb20wHhcNMjMxMTE4MjEyMjU4WhcNMzMxMTE1MjEyMjU4
WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNV
BAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2V4YW1wbGUucmVnLmNvbTEcMBoGA1UEAwwT
Y2ExLmV4YW1wbGUucmVnLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDvM
1ZgErFVgMy8gd8ChGvax9HzHHGfykPBRgxR/7DCFaKjsSqX3sO7RHU4iXaKdXTLN
WwZ5YREFyQs82vwBB2ujgc8wgcwwHQYDVR0OBBYEFJ5TxF1Te/jx0i5iCvURURRC
87gNMB8GA1UdIwQYMBaAFJ5TxF1Te/jx0i5iCvURURRC87gNMA8GA1UdEwEB/wQF
MAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF
BQcDAjBKBgNVHREEQzBBhwSsH1k0ghNjYTEuZXhhbXBsZS5yZWcuY29tghNjYTEt
ZXhhbXBsZS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAw
RQIgYcG1pQrPfndHWJAj4QFEqFgvaAx/7oE15zmm9/XiQHoCIQCcjWPaGMT5u33c
ucZHCHqAmfw0SXJSgjcQSV954KDXsQ==
-----END CERTIFICATE-----
peer"Ô
Â-----BEGIN CERTIFICATE-----
MIICsjCCAligAwIBAgIUNYpxL3n+Z6YXTBf/9gtk9QREBgYwCgYIKoZIzj0EAwIw
cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRgwFgYDVQQKDA9leGFtcGxlLnJlZy5jb20xHDAaBgNVBAMME2Nh
MS5leGFtcGxlLnJlZy5jb20wHhcNMjMxMTE4MjEyMjU4WhcNMzMxMTE1MjEyMjU4
WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNV
BAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2V4YW1wbGUucmVnLmNvbTEcMBoGA1UEAwwT
Y2ExLmV4YW1wbGUucmVnLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDvM
1ZgErFVgMy8gd8ChGvax9HzHHGfykPBRgxR/7DCFaKjsSqX3sO7RHU4iXaKdXTLN
WwZ5YREFyQs82vwBB2ujgc8wgcwwHQYDVR0OBBYEFJ5TxF1Te/jx0i5iCvURURRC
87gNMB8GA1UdIwQYMBaAFJ5TxF1Te/jx0i5iCvURURRC87gNMA8GA1UdEwEB/wQF
MAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF
BQcDAjBKBgNVHREEQzBBhwSsH1k0ghNjYTEuZXhhbXBsZS5yZWcuY29tghNjYTEt
ZXhhbXBsZS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAw
RQIgYcG1pQrPfndHWJAj4QFEqFgvaAx/7oE15zmm9/XiQHoCIQCcjWPaGMT5u33c
ucZHCHqAmfw0SXJSgjcQSV954KDXsQ==
-----END CERTIFICATE-----
admin*Ò
Â-----BEGIN CERTIFICATE-----
MIICsjCCAligAwIBAgIUNYpxL3n+Z6YXTBf/9gtk9QREBgYwCgYIKoZIzj0EAwIw
cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRgwFgYDVQQKDA9leGFtcGxlLnJlZy5jb20xHDAaBgNVBAMME2Nh
MS5leGFtcGxlLnJlZy5jb20wHhcNMjMxMTE4MjEyMjU4WhcNMzMxMTE1MjEyMjU4
WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNV
BAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2V4YW1wbGUucmVnLmNvbTEcMBoGA1UEAwwT
Y2ExLmV4YW1wbGUucmVnLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDvM
1ZgErFVgMy8gd8ChGvax9HzHHGfykPBRgxR/7DCFaKjsSqX3sO7RHU4iXaKdXTLN
WwZ5YREFyQs82vwBB2ujgc8wgcwwHQYDVR0OBBYEFJ5TxF1Te/jx0i5iCvURURRC
87gNMB8GA1UdIwQYMBaAFJ5TxF1Te/jx0i5iCvURURRC87gNMA8GA1UdEwEB/wQF
MAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF
BQcDAjBKBgNVHREEQzBBhwSsH1k0ghNjYTEuZXhhbXBsZS5yZWcuY29tghNjYTEt
ZXhhbXBsZS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAw
RQIgYcG1pQrPfndHWJAj4QFEqFgvaAx/7oE15zmm9/XiQHoCIQCcjWPaGMT5u33c
ucZHCHqAmfw0SXJSgjcQSV954KDXsQ==
-----END CERTIFICATE-----
ordererAdmins"U
WritersJ@<
 
example-reg-com
example-reg-comAdmins"9
Admins/%! 
example-reg-comAdmins">
Endorsement/%! 
example-reg-comAdmins"p
Readerse[W 
example-reg-com
example-reg-com
example-reg-comAdmins*Admins$
Capabilities


V2_0 Admins"5
LifecycleEndorsement
EndorsementAdmins""
Readers	
ReadersAdmins""
Writers	
WritersAdmins""
Admins

AdminsAdmins",
Endorsement
EndorsementAdmins*Admins”D
Orderer«D®4
reg-comú4˙2
MSPÚ2Á2‰2
reg-comú-----BEGIN CERTIFICATE-----
MIICfTCCAiSgAwIBAgIUZGleJVMUS98O8R4BkGbqRFFVWZUwCgYIKoZIzj0EAwIw
XzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29t
MB4XDTIzMTExODIxMjMzN1oXDTMzMTExNTIxMjMzN1owXzELMAkGA1UEBhMCVVMx
FzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYD
VQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29tMFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAEngd/Nb88pVco4aJDWzjU5bOpiUyXkIQvuIKPwn80sAGawWwD
vGj5MdQ150mWDrlQDzVXJ11WLOWgxpVLb6OaxKOBvTCBujAdBgNVHQ4EFgQUzLxU
Opx043wCMmfBKKHPYftF2UowHwYDVR0jBBgwFoAUzLxUOpx043wCMmfBKKHPYftF
2UowDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMDgGA1UdEQQxMC+HBKwfWTSCCmNhLnJlZy5jb22C
CmNhLXJlZy1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNHADBEAiB/
y/U4AoR28G2r1cM9cdFZ0133t5YtOngtJZQ+0oqt3wIgPSedPJt1kO6DIyaJjzLL
hmg/7uTgh+guAvC0R4GhyY8=
-----END CERTIFICATE-----
"œ-----BEGIN CERTIFICATE-----
MIICQzCCAemgAwIBAgIUNXhaqNOPX4wAArW755tr158h/R8wCgYIKoZIzj0EAwIw
XzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29t
MB4XDTIzMTExODIxMjM0M1oXDTMzMDgxNzIxMjM0M1owYDELMAkGA1UEBhMCVVMx
FzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMQ4wDAYD
VQQLDAVhZG1pbjEWMBQGA1UEAwwNQWRtaW5AcmVnLmNvbTBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABNEJehI+OK4rhM/RCaP4eXW/Pt0kv8ZQOe1vb2l95Z+PDl+x
ls4Et4LogkYiZmu0IWOp1YUKGyIjerMj3w3CwDyjgYEwfzAOBgNVHQ8BAf8EBAMC
B4AwDAYDVR0TAQH/BAIwADA+BgNVHREENzA1hwSsH1k0gg1BZG1pbkByZWcuY29t
gg1BZG1pbkByZWctY29tgglsb2NhbGhvc3SHBH8AAAEwHwYDVR0jBBgwFoAUzLxU
Opx043wCMmfBKKHPYftF2UowCgYIKoZIzj0EAwIDSAAwRQIhAIjChDaIdtot+1HH
UmChK1QsqA1MgFFd/kqJcvawTqbBAiB1446hxrEaPEonItlS/jPLqcaPVQ+CRBOV
nsto++aoRQ==
-----END CERTIFICATE-----
B
SHA2SHA256J¨-----BEGIN CERTIFICATE-----
MIICijCCAjCgAwIBAgIUJPaDVixkceU72iGyGL6/as40LvgwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRYwFAYDVQQDDA10bHNjYS5yZWcu
Y29tMB4XDTIzMTExODIxMjMzOFoXDTMzMTExNTIxMjMzOFowYjELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAw
DgYDVQQKDAdyZWcuY29tMRYwFAYDVQQDDA10bHNjYS5yZWcuY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEOHlTVLV5RrqVANteVAwESjrnGVN74+V5A/J21ZpP
0yxjl7LOKn+BVixr6i4lSHmFCvb7wReMXVme3p2RaEiWuaOBwzCBwDAdBgNVHQ4E
FgQU2/MpzjyvZJFiS6uEwmzluYfRkZMwHwYDVR0jBBgwFoAU2/MpzjyvZJFiS6uE
wmzluYfRkZMwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMD4GA1UdEQQ3MDWHBKwfWTSCDXRsc2Nh
LnJlZy5jb22CDXRsc2NhLXJlZy1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjO
PQQDAgNIADBFAiAJ/eUF+uKWQee2eJ8vMXPgIo4jbTFaVfA8zjnJTT8roQIhALxQ
zCxovyDARuMUwyiotcMms1132qWIo5wHBH3vs1wU
-----END CERTIFICATE-----
Z®ß
ú-----BEGIN CERTIFICATE-----
MIICfTCCAiSgAwIBAgIUZGleJVMUS98O8R4BkGbqRFFVWZUwCgYIKoZIzj0EAwIw
XzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29t
MB4XDTIzMTExODIxMjMzN1oXDTMzMTExNTIxMjMzN1owXzELMAkGA1UEBhMCVVMx
FzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYD
VQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29tMFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAEngd/Nb88pVco4aJDWzjU5bOpiUyXkIQvuIKPwn80sAGawWwD
vGj5MdQ150mWDrlQDzVXJ11WLOWgxpVLb6OaxKOBvTCBujAdBgNVHQ4EFgQUzLxU
Opx043wCMmfBKKHPYftF2UowHwYDVR0jBBgwFoAUzLxUOpx043wCMmfBKKHPYftF
2UowDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMDgGA1UdEQQxMC+HBKwfWTSCCmNhLnJlZy5jb22C
CmNhLXJlZy1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNHADBEAiB/
y/U4AoR28G2r1cM9cdFZ0133t5YtOngtJZQ+0oqt3wIgPSedPJt1kO6DIyaJjzLL
hmg/7uTgh+guAvC0R4GhyY8=
-----END CERTIFICATE-----
client•
ú-----BEGIN CERTIFICATE-----
MIICfTCCAiSgAwIBAgIUZGleJVMUS98O8R4BkGbqRFFVWZUwCgYIKoZIzj0EAwIw
XzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29t
MB4XDTIzMTExODIxMjMzN1oXDTMzMTExNTIxMjMzN1owXzELMAkGA1UEBhMCVVMx
FzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYD
VQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29tMFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAEngd/Nb88pVco4aJDWzjU5bOpiUyXkIQvuIKPwn80sAGawWwD
vGj5MdQ150mWDrlQDzVXJ11WLOWgxpVLb6OaxKOBvTCBujAdBgNVHQ4EFgQUzLxU
Opx043wCMmfBKKHPYftF2UowHwYDVR0jBBgwFoAUzLxUOpx043wCMmfBKKHPYftF
2UowDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMDgGA1UdEQQxMC+HBKwfWTSCCmNhLnJlZy5jb22C
CmNhLXJlZy1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNHADBEAiB/
y/U4AoR28G2r1cM9cdFZ0133t5YtOngtJZQ+0oqt3wIgPSedPJt1kO6DIyaJjzLL
hmg/7uTgh+guAvC0R4GhyY8=
-----END CERTIFICATE-----
peer"¶
ú-----BEGIN CERTIFICATE-----
MIICfTCCAiSgAwIBAgIUZGleJVMUS98O8R4BkGbqRFFVWZUwCgYIKoZIzj0EAwIw
XzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29t
MB4XDTIzMTExODIxMjMzN1oXDTMzMTExNTIxMjMzN1owXzELMAkGA1UEBhMCVVMx
FzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYD
VQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29tMFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAEngd/Nb88pVco4aJDWzjU5bOpiUyXkIQvuIKPwn80sAGawWwD
vGj5MdQ150mWDrlQDzVXJ11WLOWgxpVLb6OaxKOBvTCBujAdBgNVHQ4EFgQUzLxU
Opx043wCMmfBKKHPYftF2UowHwYDVR0jBBgwFoAUzLxUOpx043wCMmfBKKHPYftF
2UowDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMDgGA1UdEQQxMC+HBKwfWTSCCmNhLnJlZy5jb22C
CmNhLXJlZy1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNHADBEAiB/
y/U4AoR28G2r1cM9cdFZ0133t5YtOngtJZQ+0oqt3wIgPSedPJt1kO6DIyaJjzLL
hmg/7uTgh+guAvC0R4GhyY8=
-----END CERTIFICATE-----
admin*®
ú-----BEGIN CERTIFICATE-----
MIICfTCCAiSgAwIBAgIUZGleJVMUS98O8R4BkGbqRFFVWZUwCgYIKoZIzj0EAwIw
XzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29t
MB4XDTIzMTExODIxMjMzN1oXDTMzMTExNTIxMjMzN1owXzELMAkGA1UEBhMCVVMx
FzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYD
VQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29tMFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAEngd/Nb88pVco4aJDWzjU5bOpiUyXkIQvuIKPwn80sAGawWwD
vGj5MdQ150mWDrlQDzVXJ11WLOWgxpVLb6OaxKOBvTCBujAdBgNVHQ4EFgQUzLxU
Opx043wCMmfBKKHPYftF2UowHwYDVR0jBBgwFoAUzLxUOpx043wCMmfBKKHPYftF
2UowDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMDgGA1UdEQQxMC+HBKwfWTSCCmNhLnJlZy5jb22C
CmNhLXJlZy1jb22CCWxvY2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNHADBEAiB/
y/U4AoR28G2r1cM9cdFZ0133t5YtOngtJZQ+0oqt3wIgPSedPJt1kO6DIyaJjzLL
hmg/7uTgh+guAvC0R4GhyY8=
-----END CERTIFICATE-----
ordererAdmins"1
Admins' 
reg-comAdmins"0
Readers% 	
reg-comAdmins"0
Writers% 	
reg-comAdmins*Admins$
Capabilities


V2_0 AdminsÓ
ConsensusType‹—
etcdraftƒ
≠
172.31.89.52ﬁ6À-----BEGIN CERTIFICATE-----
MIICQDCCAeagAwIBAgIUQQAavzUIVkk11h1xK1Uxz0q2iqkwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRYwFAYDVQQDDA10bHNjYS5yZWcu
Y29tMB4XDTIzMTExODIxMjM1MFoXDTMzMDgxNzIxMjM1MFowUzELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRkw
FwYDVQQDDBBvcmRlcmVyMS5yZWcuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
QgAEyhqg+9dMpyRjphsow5g0FJQvi2fZxsuP9Si+Yp8cwIWLgkZRLky8T34nQBTH
bFRK5JzGrWT3ZFjkqjG1fN9EsqOBiDCBhTAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0T
AQH/BAIwADBEBgNVHREEPTA7hwSsH1k0ghBvcmRlcmVyMS5yZWcuY29tghBvcmRl
cmVyMS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwHwYDVR0jBBgwFoAU2/Mpzjyv
ZJFiS6uEwmzluYfRkZMwCgYIKoZIzj0EAwIDSAAwRQIhAOlSt2nl/10nS2iE4Vtq
zrm9UU4ZDzT0XsZJjh4bGVdYAiAtJZvK1q+JRbGyI1hM3IcemO3Z6/L9JM+DGMp8
j+VCrw==
-----END CERTIFICATE-----
"À-----BEGIN CERTIFICATE-----
MIICQDCCAeagAwIBAgIUQQAavzUIVkk11h1xK1Uxz0q2iqkwCgYIKoZIzj0EAwIw
YjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRYwFAYDVQQDDA10bHNjYS5yZWcu
Y29tMB4XDTIzMTExODIxMjM1MFoXDTMzMDgxNzIxMjM1MFowUzELMAkGA1UEBhMC
VVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRkw
FwYDVQQDDBBvcmRlcmVyMS5yZWcuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
QgAEyhqg+9dMpyRjphsow5g0FJQvi2fZxsuP9Si+Yp8cwIWLgkZRLky8T34nQBTH
bFRK5JzGrWT3ZFjkqjG1fN9EsqOBiDCBhTAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0T
AQH/BAIwADBEBgNVHREEPTA7hwSsH1k0ghBvcmRlcmVyMS5yZWcuY29tghBvcmRl
cmVyMS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwHwYDVR0jBBgwFoAU2/Mpzjyv
ZJFiS6uEwmzluYfRkZMwCgYIKoZIzj0EAwIDSAAwRQIhAOlSt2nl/10nS2iE4Vtq
zrm9UU4ZDzT0XsZJjh4bGVdYAiAtJZvK1q+JRbGyI1hM3IcemO3Z6/L9JM+DGMp8
j+VCrw==
-----END CERTIFICATE-----

500ms
 (ÄÄÄAdmins"
	BatchSize
ÄÄ¿1ÄÄ Admins
BatchTimeout
2sAdmins
ChannelRestrictionsAdmins""
Writers	
WritersAdmins""
Admins

AdminsAdmins"*
BlockValidation	
WritersAdmins""
Readers	
ReadersAdmins*AdminsB
OrdererAddresses.
172.31.89.52:7006/Channel/Orderer/Admins$
Capabilities


V2_0 Admins*

Consortium
SampleConsortiumAdmins&
HashingAlgorithm
SHA256Admins-
BlockDataHashingStructureˇˇˇˇAdmins""
Writers	
WritersAdmins""
Admins

AdminsAdmins""
Readers	
ReadersAdmins*AdminsŸ
é
⁄
…ÂÈ™"autochannelæ
°
example2-reg-comå-----BEGIN CERTIFICATE-----
MIICcTCCAhigAwIBAgIUEGpa4dBx+/sQy23HQBlksYSm+eIwCgYIKoZIzj0EAwIw
cjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBleGFtcGxlMi5yZWcuY29tMR0wGwYDVQQDDBRj
YTEuZXhhbXBsZTIucmVnLmNvbTAeFw0yMzExMTgyMTIzMjNaFw0zMzA4MTcyMTIz
MjNaMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
A1UEBwwHUmFsZWlnaDEOMAwGA1UECwwFYWRtaW4xHzAdBgNVBAMMFkFkbWluQGV4
YW1wbGUyLnJlZy5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATFlZP3+uBJ
VhC4wt28hLVT4G+2HC8yHUEKkgSK+uWwQ8noGD1ur1S/l25CWqyRd0Ha8dqHk4QP
ZAacCx+8wuC8o4GUMIGRMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMFAG
A1UdEQRJMEeHBKwfWTSCFkFkbWluQGV4YW1wbGUyLnJlZy5jb22CFkFkbWluQGV4
YW1wbGUyLXJlZy1jb22CCWxvY2FsaG9zdIcEfwAAATAfBgNVHSMEGDAWgBRyBsqu
dtPVsvUfOsd/Cky9pKGPgzAKBggqhkjOPQQDAgNHADBEAiAXcQ97B+ntC1ZQHYzT
jQ/CiHf+yWk3/0Uo7d//2dhpEwIgILFrEOqpijBt6+OeUziu7l3I4RtpdJDYpao4
KfdJXHk=
-----END CERTIFICATE-----
 K<=ãKv”†Õôæ–{S˙Ì´ ±ÂòÆ

ü
autochannelig
ApplicationXT
example2-reg-com@
MSP "

Admins "
Endorsement "
Readers "
Writers §°
Applicationëå
example2-reg-comx,
AnchorPeers

172.31.89.52€6Admins
MSP "

Admins "
Endorsement "
Readers "
Writers *Adminsâ
æ
°
example2-reg-comå-----BEGIN CERTIFICATE-----
MIICcTCCAhigAwIBAgIUEGpa4dBx+/sQy23HQBlksYSm+eIwCgYIKoZIzj0EAwIw
cjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRkwFwYDVQQKDBBleGFtcGxlMi5yZWcuY29tMR0wGwYDVQQDDBRj
YTEuZXhhbXBsZTIucmVnLmNvbTAeFw0yMzExMTgyMTIzMjNaFw0zMzA4MTcyMTIz
MjNaMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
A1UEBwwHUmFsZWlnaDEOMAwGA1UECwwFYWRtaW4xHzAdBgNVBAMMFkFkbWluQGV4
YW1wbGUyLnJlZy5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATFlZP3+uBJ
VhC4wt28hLVT4G+2HC8yHUEKkgSK+uWwQ8noGD1ur1S/l25CWqyRd0Ha8dqHk4QP
ZAacCx+8wuC8o4GUMIGRMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMFAG
A1UdEQRJMEeHBKwfWTSCFkFkbWluQGV4YW1wbGUyLnJlZy5jb22CFkFkbWluQGV4
YW1wbGUyLXJlZy1jb22CCWxvY2FsaG9zdIcEfwAAATAfBgNVHSMEGDAWgBRyBsqu
dtPVsvUfOsd/Cky9pKGPgzAKBggqhkjOPQQDAgNHADBEAiAXcQ97B+ntC1ZQHYzT
jQ/CiHf+yWk3/0Uo7d//2dhpEwIgILFrEOqpijBt6+OeUziu7l3I4RtpdJDYpao4
KfdJXHk=
-----END CERTIFICATE-----
√*q◊ŸVe?Ñ˜5ìpSêŸoP2Ñx˜ÈF0D A"@˙πÅE„æÇöáÕzŸ}àa+Ê{Ä∫æŒ„Å"& §[ﬁa¢˝†Ñ5eÇ™ŸÕyó¯#7^3ß›OÑ&,F0D Q™˜ƒºÅQ)Ñ’"Ã ∂¢jöÂ;ïØﬁ}˝'8Ô<îª‹ ÒAë>ÆÆFü–&$ßÚÇñP&‰ãh,zó#îDF0D L[ãj‡h+y	»ÖN[æ∏°‹l%∞˚ì8Í◊◊w õÓóŒïôÄ@>%ë.√ƒ}’M∂ªÒ¥ª®©›ß·˜
Ë

	

‘
à
Î
reg-comﬂ-----BEGIN CERTIFICATE-----
MIICTzCCAfWgAwIBAgIUNXhaqNOPX4wAArW755tr158h/SAwCgYIKoZIzj0EAwIw
XzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH
DAdSYWxlaWdoMRAwDgYDVQQKDAdyZWcuY29tMRMwEQYDVQQDDApjYS5yZWcuY29t
MB4XDTIzMTExODIxMjM0OVoXDTMzMDgxNzIxMjM0OVowZTELMAkGA1UEBhMCVVMx
FzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYD
VQQLDAdvcmRlcmVyMRkwFwYDVQQDDBBvcmRlcmVyMS5yZWcuY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEdQ+3qBKer6B87l8jPmXQCDltDyJulPs5IxnQg9zc
Zw1lV1gUGrLUXctJp2cmahz8+kyqxTIKaRYt04bnU9we/KOBiDCBhTAOBgNVHQ8B
Af8EBAMCB4AwDAYDVR0TAQH/BAIwADBEBgNVHREEPTA7hwSsH1k0ghBvcmRlcmVy
MS5yZWcuY29tghBvcmRlcmVyMS1yZWctY29tgglsb2NhbGhvc3SHBH8AAAEwHwYD
VR0jBBgwFoAUzLxUOpx043wCMmfBKKHPYftF2UowCgYIKoZIzj0EAwIDSAAwRQIh
AN+W5rWPVbubloS0ioo8HAp+4e/eVUCYINmSiNZHRW9lAiB8MSyXtDrWLHfjE6Y3
fOtxtxqxgVhvvYjbXSiibUKJgA==
-----END CERTIFICATE-----
s˝t}–î∞ÑA≤ﬁu+Ôà≤pçÉG0E! ô{*¶ÊÄVÛŒ˙fÀÌ"@N˝J4 ûÇxF◊öö uß¸∆˝éõ≥xU∆3_Ÿ·∑Õ†π¡ƒª3@„v


 
 
 